// GET de todos los comercios.
GET http://localhost:3000/api/comercio HTTP/1.1

###

// GET de un comercio por su CIF.
GET http://localhost:3000/api/comercio/B00116546 HTTP/1.1

###

// Creación de un comercio.
POST http://localhost:3000/api/comercio HTTP/1.1
Content-Type: application/json

{
  "name": "Coffee Delight",
  "cif": "B23456789",
  "city": "Madrid",
  "email": "info@coffeedelight.com",
  "phone": "+34 91 123 4567",
  "cover": "coffee_delight.jpg",
  "description": "Coffee Delight is a cozy and inviting coffee shop where the rich aroma of freshly brewed coffee welcomes you upon entry. With its warm and modern ambiance, Coffee Delight is the perfect haven for coffee enthusiasts and those seeking a delightful break. Offering a curated selection of premium coffee blends, artisanal pastries, and a tranquil atmosphere, this charming coffee destination promises a delightful experience for every sip and moment shared with friends or in quiet contemplation.",
  "activity": "Food",
  "images": [],
  "reviews": [
    "Cozy ambiance, amazing coffee!",
    "Perfect spot for coffee lovers.",
    "Delightful experience every visit."
  ],
  "score": 0,
  "upvotes": 0,
  "downvotes": 0
}

###

// Creación de un comercio.
POST http://localhost:3000/api/comercio HTTP/1.1
Content-Type: application/json

{
  "name": "Sweet Delight",
  "cif": "B1857354",
  "city": "Valencia",
  "email": "info@sweetparadise.com",
  "phone": "+34 96 444 4444",
  "cover": "sweet_paradise.jpg",
  "description": "Welcome to Sweet Paradise, where every visit is a journey into a world of delectable delights! Step into a whimsical wonderland of candies and confections, where vibrant colors and tempting aromas invite you to indulge your sweetest cravings. From classic favorites to artisanal treats, Sweet Paradise is a haven for candy enthusiasts of all ages. Immerse yourself in a sugar-coated haven where every corner holds a new surprise, making your experience at Sweet Paradise a truly enchanting adventure in the realm of sweetness.",
  "activity": "Food",
  "images": [],
  "reviews": [
    "A sweet lover's dream!",
    "Whimsical and delicious treats.",
    "Enchanting adventure in sweetness."
  ],
  "score": 0,
  "upvotes": 0,
  "downvotes": 0,
  "votesNum": 0
}

###

// Modificación de un comercio pos su CIF.
PUT http://localhost:3000/api/comercio/B00116546 HTTP/1.1
Content-Type: application/json

{
  "name": "Coffes Delight",
  "cif": "B00116546",
  "direccion": "Calle Antonio Machado",
  "email": "example@example.com",
  "telefonoContacto": "123456789",
  "idPagina": 1,
  "description": "Very good food.",
  "reviews": ["Very nice", "Tasty!"]
}

###

// Eliminación de un comercio por su CIF. Tipo es un parámetro query (fisico o logico).
DELETE http://localhost:3000/api/comercio/B00116546?tipo=fisico

###